In [4]:
# 导入 numpy

In [5]:
import numpy as np 

In [12]:
# 创建矩阵

In [7]:
np.identity(3)  # 创建一个3*3的单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.zeros([3,3])  # 创建一个3*3的零矩阵

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.random.rand(3,3)  # 创建一个3*3的随机矩阵

array([[0.04499348, 0.35153337, 0.83896233],
       [0.40358966, 0.73604089, 0.01549123],
       [0.74795795, 0.48916796, 0.38737998]])

In [11]:
np.asarray([1,2,3,4]).reshape(2,2)  # 从已有数组创建矩阵，asarray将Python列表转换成一维数组，reshape重塑矩阵形状

array([[1, 2],
       [3, 4]])

In [13]:
# 判断两个矩阵是否相等

In [17]:
# allclose，比较两个array是不是每一元素都相等，返回 True/False，默认在1e-05的误差范围内

In [18]:
print("零矩阵和单位矩阵", np.allclose(np.zeros([3,3]), np.identity(3)))
print("单位矩阵和单位矩阵", np.allclose(np.identity(3), np.identity(3)))

零矩阵和单位矩阵 False
单位矩阵和单位矩阵 True


In [19]:
# 计算矩阵

In [20]:
# 矩阵加法 np.add /减法 np.subtract

In [22]:
A = np.asarray([1,2,3,4]).reshape(2,2)
B = np.identity(2)
print(np.add(A,B))
print(np.subtract(A,B))

[[2. 2.]
 [3. 5.]]
[[0. 2.]
 [3. 3.]]


In [23]:
# 矩阵乘法 np.dot

In [24]:
# （前提同形）任何矩阵乘上零矩阵等于零矩阵，任何矩阵乘上单位矩阵等于其本身
A = np.asarray([1,2,3,4]).reshape(2,2)
B = np.zeros([2,2])
C = np.identity(2)
print(np.dot(A,B))
print(np.dot(A,C))

[[0. 0.]
 [0. 0.]]
[[1. 2.]
 [3. 4.]]


In [25]:
# 矩阵求逆 np.linalg.inv

In [28]:
# 矩阵的逆与矩阵的乘积为单位矩阵
A = np.asarray([1,2,3,4]).reshape(2,2)
A_INV = np.linalg.inv(A)
print(A_INV)
print(np.dot(A,A_INV))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [35]:
# 不是所有的矩阵都有逆，比如零矩阵就没有逆，如果尝试用numpy来求逆则会出现错误
O = np.zeros(2)
# O_INV = np.linalg.inv(O)

In [36]:
c = np.asarray([
    1,2,3,
    4,5,6,
    7,8,9,
]).reshape((3,3))
print("矩阵的行列式：", np.linalg.det(c))
print("矩阵的秩：", np.linalg.matrix_rank(c))
c_inv = np.linalg.inv(c)
print("矩阵c和c_inv点乘的结果：\n", np.dot(c,c_inv))

矩阵的行列式： 6.66133814775094e-16
矩阵的秩： 2
矩阵c和c_inv点乘的结果：
 [[ 0.  0.  0.]
 [-4.  0. -4.]
 [ 0.  0.  0.]]


In [37]:
# 矩阵转置 .T

In [38]:
A = np.asarray([1,2,3,4]).reshape(2,2)
A.T

array([[1, 3],
       [2, 4]])