In [5]:
# 四元数:quaternions
# 四元数模块在transforms3d.quaternions里

In [6]:
# 四元数与旋转矩阵互转

import transforms3d as tfs
import numpy as np
# 四元数转旋转矩阵
tfs.quaternions.quat2mat([1,0,0,0])
# 旋转矩阵转四元数
tfs.quaternions.mat2quat(np.asarray([[1., 0., 0.],[0., 1., 0.],[0., 0., 1.]]))

array([1., 0., 0., 0.])

In [13]:
# 四元数与轴角互转

import transforms3d as tfs
import numpy as np
# 四元数转旋轴角
tfs.quaternions.quat2axangle([1,0,0,0])
# 轴角转四元数
tfs.quaternions.axangle2quat([1,0,0],0.5)

array([0.96891242, 0.24740396, 0.        , 0.        ])

In [8]:
# 欧拉:euler
# 欧拉角模块在transforms3d.euler里

In [9]:
# 欧拉角与四元数互转

import transforms3d as tfs
import numpy as np
# 固定轴欧拉角转四元数
tfs.euler.euler2quat(0,0,0,"sxyz")
# 四元数转固定轴欧拉角
tfs.euler.quat2euler([1,0,0,0],"sxyz")

(0.0, -0.0, 0.0)

In [10]:
# 欧拉角与旋转矩阵互转

import transforms3d as tfs
import numpy as np 
# 固定轴欧拉角转旋转矩阵
tfs.euler.euler2mat(0,0,0,"sxyz")
# 旋转矩阵转固定轴欧拉角
tfs.euler.mat2euler(np.asarray([[1., 0., 0.],[0., 1., 0.],[0., 0., 1.]]),"sxyz")

(0.0, -0.0, 0.0)

In [12]:
# 欧拉角与轴角互转

import transforms3d as tfs
import numpy as np
# 固定轴欧拉角轴角
tfs.euler.euler2axangle(0,0,0,"sxyz")
# 轴角转固定轴欧拉角
tfs.euler.axangle2euler([1,0,0],0.5,"sxyz")

(0.5, -0.0, 0.0)

In [14]:
# 轴角:axangles
# 轴角模块在transforms3d.axangle里

In [18]:
# 轴角与旋转矩阵互转

import transforms3d as tfs
import numpy as np 
# 轴角转旋转矩阵
tfs.axangles.axangle2mat([1,0,0],0.5)
# 旋转矩阵转轴角
tfs.axangles.mat2axangle(np.asarray([[1., 0., 0.],[0., 1., 0.],[0., 0., 1.]]))

(array([0., 0., 1.]), 0.0)