In [2]:
import numpy as np # 导入numpy

In [3]:
# 位置表示

In [6]:
# 位置矩阵
# 使用3*1的矩阵表示位置
np.asarray([1.0,1.0,1.0]).reshape(3,1) # 新建一个沿着x、y、z各平移1个单位的位置矢量

array([[1.],
       [1.],
       [1.]])

In [7]:
# 姿态表示
# 姿态可以使用3*3的旋转矩阵表示，3*3的单位矩阵代表没有姿态变换（意没有姿态变换不是零矩阵，而是单位矩阵）
# 新建一个旋转矩阵，用该旋转矩阵表示绕着z轴旋转45度
import math
import numpy as np
theta = math.radians(45)
R_AB = np.asarray([math.cos(theta),-math.sin(theta),0,
                   math.sin(theta),math.cos(theta),0,
                   0,0,1
                  ]).reshape(3,3)
print(R_AB)

[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


In [8]:
# numpy坐标变换

In [9]:
#1.相机坐标系{C}为参考坐标系，工具坐标系{P}的位置矢量在相机坐标系{C}的x,y,z各轴投影为2,1,2，并且工具坐标系和相机坐标系姿态相同
#2.机器人基坐标系{B}为参考坐标系，相机坐标系{C}的位置矢量在{B}各轴的投影为 0,0,3，坐标系{C}绕着坐标系{B}的x轴转了180度
#求：{B}为参考坐标系，坐标系{P}的位置矢量和旋转矩阵

In [11]:
# 旋转矩阵求解

# (1) R_BP = R_BC ​ R_CP
# (2) {C}和{P}姿态相同，所以R_PC是一个单位矩阵
# (3) {C}绕着{B}的x旋转了180度，根据重要公式可知
# R(x,\theta)= \begin{bmatrix}
# 1 & 0 & 0\
# 0 & {cos\theta} & -sin\theta \
# 0&{sin\theta} & cos\theta \
# \end{bmatrix} 

# R_BC
import math
import numpy as np
theta = math.radians(180)
R_BC = np.asarray([1,0,0,
                   0,math.cos(theta),-math.sin(theta),
                   0,math.sin(theta),math.cos(theta)]).reshape(3,3)
# R_BP
R_BP = R_BC * np.identity(3)
print("旋转矩阵R_BP:\n",R_BP)

旋转矩阵R_BP：
 [[ 1.  0.  0.]
 [ 0. -1. -0.]
 [ 0.  0. -1.]]


In [12]:
# 平移矩阵求解

# P_BP = R_BC ​ P_CP + P_BC
# 由题意得 P_BC=[0,0,3]^T, P_CP=[2,1,2]^T

P_BC = np.asarray([0,0,3]).reshape(3,1)
P_CP = np.asarray([2,1,2]).reshape(3,1)
P_BP = np.add(np.dot(R_BC,P_CP),P_BC)
print("位置矢量P_BP:\n",P_BP.T)

位置矢量P_BP:
 [[ 2. -1.  1.]]
